<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-U73UTOG" failures="1" tests="4" name="SubmitOrder" time="25.56" errors="0" timestamp="2025-04-03T14:55:29 GMT-04:00">
  <testcase classname="tests.StandAlone" name="SubmitOrder" time="3.663"/>
  <testcase classname="tests.StandAlone" name="SubmitOrder" time="3.797"/>
  <testcase classname="tests.StandAlone" name="submittwo" time="0.001"/>
  <testcase classname="tests.StandAlone" name="OrderHistoryTest" time="0.98">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.StandAlone.OrderHistoryTest(StandAlone.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- OrderHistoryTest -->
</testsuite> <!-- SubmitOrder -->
